name: RiskRunner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: 6.0.7  
  mapbox_maps_flutter: ^2.1.0   
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_core_web: ^3.4.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  custom_timer: ^0.2.1
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.2
  share_plus: 12.0.1
  firebase_messaging: ^16.1.2
  http: ^1.2.0
  purchases_flutter: ^9.13.1  
  purchases_ui_flutter: ^9.13.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Mapa_risk.png
    - assets/avatars/
    - assets/avatars/base/
    - assets/avatars/hair/
    # - assets/avatars/eyes/      ← comentadas hasta tener contenido
    # - assets/avatars/jacket/
    # - assets/avatars/pants/
    # - assets/avatars/shoes/