// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCNQ4C7AcZiUyABVM-PcDZCU3aCC-ypg',
    appId: '1:1097151479835:web:2487ea31c9c82b9329f8be',
    messagingSenderId: '1097151479835',
    projectId: 'runnerriskapp',
    authDomain: 'runnerriskapp.firebaseapp.com',
    storageBucket: 'runnerriskapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwKim5ZD0xTPqkWdcXXJRi2sAD8BoHA44',
    appId: '1:1097151479835:android:1f274b208d2e924b29f8be',
    messagingSenderId: '1097151479835',
    projectId: 'runnerriskapp',
    storageBucket: 'runnerriskapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2QrG8H6jbYq8-LpRLOSpTBSNxvUlf70E',
    appId: '1:1097151479835:ios:096eaf7f9ad16e5629f8be',
    messagingSenderId: '1097151479835',
    projectId: 'runnerriskapp',
    storageBucket: 'runnerriskapp.firebasestorage.app',
    iosBundleId: 'com.riskrunner.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2QrG8H6jbYq8-LpRLOSpTBSNxvUlf70E',
    appId: '1:1097151479835:ios:922db57ace27c4cc29f8be',
    messagingSenderId: '1097151479835',
    projectId: 'runnerriskapp',
    storageBucket: 'runnerriskapp.firebasestorage.app',
    iosBundleId: 'com.example.miApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxCNQ4C7AcZiUyABVM-PcDZCU3aCC-ypg',
    appId: '1:1097151479835:web:c7413be7b3d92cea29f8be',
    messagingSenderId: '1097151479835',
    projectId: 'runnerriskapp',
    authDomain: 'runnerriskapp.firebaseapp.com',
    storageBucket: 'runnerriskapp.firebasestorage.app',
  );
}
